import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

class ReportGenerator:
    def __init__(self, dataframe):
        self.df = dataframe
        self.temp_image = "temp_chart.png"

    def create_visuals(self):
        if self.df.empty:
            print("No data available to create charts.")
            return False

        print("Generating expense distribution chart...")
        # Grouping data by category
        category_totals = self.df.groupby('Category')['Amount'].sum()
        
        # Creating the plot
        plt.figure(figsize=(6, 4))
        category_totals.plot(kind='pie', autopct='%1.1f%%', startangle=140, colors=['#ff9999','#66b3ff','#99ff99','#ffcc99'])
        plt.title('Spending Distribution by Category')
        plt.ylabel('') # Remove the 'Amount' label from the side
        
        plt.tight_layout()
        plt.savefig(self.temp_image)
        plt.close()
        return True

    def generate_pdf(self, output_name="Financial_Report.pdf"):
        """
        Generates a professional multi-page PDF report.
        Page 1: Transaction list with automatic page overflow.
        Page 2: Full-page data visualization chart.
        """
        print(f"Creating PDF report: {output_name}...")
        c = canvas.Canvas(output_name, pagesize=letter)
        width, height = letter

        # --- PAGE 1: HEADER & TRANSACTION LIST ---
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 50, "Monthly Financial Summary")
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, "Generated by FinTrack Automated System")
        c.line(50, height - 80, 550, height - 80)

        # Starting position for the list
        y = height - 120
        c.setFont("Helvetica", 10)

        # Loop through data and print rows
        for index, row in self.df.iterrows():
            text = f"• {row['Vendor']} ({row['Category']}): Rs. {row['Amount']}"
            c.drawString(70, y, text)
            y -= 20
            
            # If the list reaches the bottom, start a new page for more text
            if y < 50:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 10)

        # --- THE FIX: MOVE CHART TO A FRESH PAGE ---
        c.showPage() 

        # --- PAGE 2: VISUAL ANALYTICS ---
        c.setFont("Helvetica-Bold", 16)
        c.drawCentredString(width / 2, height - 50, "Spending Distribution by Category")
        
        # Draw the chart saved by create_visuals() in Step 2
        # Ensure 'temp_chart.png' exists before trying to draw it
        if os.path.exists("temp_chart.png"):
            # Centers a 400px wide image on the page
            c.drawImage("temp_chart.png", (width - 400) / 2, height - 500, width=400, height=400)
        else:
            c.setFont("Helvetica-Oblique", 10)
            c.drawCentredString(width / 2, height - 200, "[Technical Alert: Chart image not found]")
        
        # Save the final PDF
        c.save()
        
        # Cleanup: Delete the temporary chart image to keep the project folder clean
        if os.path.exists("temp_chart.png"):
            os.remove("temp_chart.png")
            
        print(f"--- System: Multi-page report saved as {output_name} ---")