import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

class ReportGenerator:
    def __init__(self, dataframe):
        self.df = dataframe
        self.temp_image = "temp_chart.png"

    def create_visuals(self):
        if self.df.empty:
            print("No data available to create charts.")
            return False

        print("Generating expense distribution chart...")
        # Grouping data by category
        category_totals = self.df.groupby('Category')['Amount'].sum()
        
        # Creating the plot
        plt.figure(figsize=(6, 4))
        category_totals.plot(kind='pie', autopct='%1.1f%%', startangle=140, colors=['#ff9999','#66b3ff','#99ff99','#ffcc99'])
        plt.title('Spending Distribution by Category')
        plt.ylabel('') # Remove the 'Amount' label from the side
        
        plt.tight_layout()
        plt.savefig(self.temp_image)
        plt.close()
        return True

    def generate_pdf(self, output_name="Financial_Report.pdf"):
        print(f"Creating PDF report: {output_name}...")
        
        c = canvas.Canvas(output_name, pagesize=letter)
        width, height = letter

        # Header Section
        c.setFont("Helvetica-Bold", 20)
        c.drawString(100, height - 50, "Monthly Financial Summary")
        
        c.setFont("Helvetica", 12)
        c.drawString(100, height - 70, "Generated by FinTrack Automated System")
        c.line(100, height - 80, 500, height - 80)

        # Body - List Transactions
        y_position = height - 120
        c.setFont("Helvetica-Bold", 14)
        c.drawString(100, y_position, "Transaction Breakdown:")
        y_position -= 20
        
        c.setFont("Helvetica", 10)
        for index, row in self.df.iterrows():
            text = f"- {row['Vendor']} ({row['Category']}): Rs. {row['Amount']}"
            c.drawString(120, y_position, text)
            y_position -= 15
            if y_position < 400: # Simple page overflow check
                break

        # Adding the Chart
        if os.path.exists(self.temp_image):
            c.drawImage(self.temp_image, 100, 100, width=400, preserveAspectRatio=True)
        
        c.showPage()
        c.save()
        
        # Clean up the temporary image file
        if os.path.exists(self.temp_image):
            os.remove(self.temp_image)
            
        print("PDF Report successfully generated!")